#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("MasterMind.Resource", IsApplication=true)]

namespace MasterMind
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f040000
			public const int Grey1 = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int Grey2 = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int Grey3 = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int Grey4 = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int Grey5 = 2130968580;
			
			// aapt resource value: 0x7f040007
			public const int MyBlue = 2130968583;
			
			// aapt resource value: 0x7f040006
			public const int MyGreen = 2130968582;
			
			// aapt resource value: 0x7f040008
			public const int MyPink = 2130968584;
			
			// aapt resource value: 0x7f040009
			public const int MyRed = 2130968585;
			
			// aapt resource value: 0x7f040005
			public const int MyYellow = 2130968581;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int BlackRect = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int BlueCircle = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int Border = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int Border2 = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int GreenCircle = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int GreyCircle = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int Icon = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int monoandroidsplash = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int PinkCircle = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int RedCircle = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int WhiteRect = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int YellowCircle = 2130837515;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070053
			public const int ButtonInstruction = 2131165267;
			
			// aapt resource value: 0x7f070052
			public const int ButtonPlay = 2131165266;
			
			// aapt resource value: 0x7f070049
			public const int C101 = 2131165257;
			
			// aapt resource value: 0x7f07004a
			public const int C102 = 2131165258;
			
			// aapt resource value: 0x7f07004b
			public const int C103 = 2131165259;
			
			// aapt resource value: 0x7f07004c
			public const int C104 = 2131165260;
			
			// aapt resource value: 0x7f07004d
			public const int C105 = 2131165261;
			
			// aapt resource value: 0x7f07004e
			public const int CheckButton = 2131165262;
			
			// aapt resource value: 0x7f070001
			public const int F21 = 2131165185;
			
			// aapt resource value: 0x7f070002
			public const int F22 = 2131165186;
			
			// aapt resource value: 0x7f070003
			public const int F23 = 2131165187;
			
			// aapt resource value: 0x7f070004
			public const int F24 = 2131165188;
			
			// aapt resource value: 0x7f070005
			public const int F25 = 2131165189;
			
			// aapt resource value: 0x7f070006
			public const int F251 = 2131165190;
			
			// aapt resource value: 0x7f070007
			public const int F252 = 2131165191;
			
			// aapt resource value: 0x7f070008
			public const int F253 = 2131165192;
			
			// aapt resource value: 0x7f070009
			public const int F254 = 2131165193;
			
			// aapt resource value: 0x7f07000a
			public const int F31 = 2131165194;
			
			// aapt resource value: 0x7f07000b
			public const int F32 = 2131165195;
			
			// aapt resource value: 0x7f07000c
			public const int F33 = 2131165196;
			
			// aapt resource value: 0x7f07000d
			public const int F34 = 2131165197;
			
			// aapt resource value: 0x7f07000e
			public const int F35 = 2131165198;
			
			// aapt resource value: 0x7f07000f
			public const int F351 = 2131165199;
			
			// aapt resource value: 0x7f070010
			public const int F352 = 2131165200;
			
			// aapt resource value: 0x7f070011
			public const int F353 = 2131165201;
			
			// aapt resource value: 0x7f070012
			public const int F354 = 2131165202;
			
			// aapt resource value: 0x7f070013
			public const int F41 = 2131165203;
			
			// aapt resource value: 0x7f070014
			public const int F42 = 2131165204;
			
			// aapt resource value: 0x7f070015
			public const int F43 = 2131165205;
			
			// aapt resource value: 0x7f070016
			public const int F44 = 2131165206;
			
			// aapt resource value: 0x7f070017
			public const int F45 = 2131165207;
			
			// aapt resource value: 0x7f070018
			public const int F451 = 2131165208;
			
			// aapt resource value: 0x7f070019
			public const int F452 = 2131165209;
			
			// aapt resource value: 0x7f07001a
			public const int F453 = 2131165210;
			
			// aapt resource value: 0x7f07001b
			public const int F454 = 2131165211;
			
			// aapt resource value: 0x7f07001c
			public const int F51 = 2131165212;
			
			// aapt resource value: 0x7f07001d
			public const int F52 = 2131165213;
			
			// aapt resource value: 0x7f07001e
			public const int F53 = 2131165214;
			
			// aapt resource value: 0x7f07001f
			public const int F54 = 2131165215;
			
			// aapt resource value: 0x7f070020
			public const int F55 = 2131165216;
			
			// aapt resource value: 0x7f070021
			public const int F551 = 2131165217;
			
			// aapt resource value: 0x7f070022
			public const int F552 = 2131165218;
			
			// aapt resource value: 0x7f070023
			public const int F553 = 2131165219;
			
			// aapt resource value: 0x7f070024
			public const int F554 = 2131165220;
			
			// aapt resource value: 0x7f070025
			public const int F61 = 2131165221;
			
			// aapt resource value: 0x7f070026
			public const int F62 = 2131165222;
			
			// aapt resource value: 0x7f070027
			public const int F63 = 2131165223;
			
			// aapt resource value: 0x7f070028
			public const int F64 = 2131165224;
			
			// aapt resource value: 0x7f070029
			public const int F65 = 2131165225;
			
			// aapt resource value: 0x7f07002a
			public const int F651 = 2131165226;
			
			// aapt resource value: 0x7f07002b
			public const int F652 = 2131165227;
			
			// aapt resource value: 0x7f07002c
			public const int F653 = 2131165228;
			
			// aapt resource value: 0x7f07002d
			public const int F654 = 2131165229;
			
			// aapt resource value: 0x7f07002e
			public const int F71 = 2131165230;
			
			// aapt resource value: 0x7f07002f
			public const int F72 = 2131165231;
			
			// aapt resource value: 0x7f070030
			public const int F73 = 2131165232;
			
			// aapt resource value: 0x7f070031
			public const int F74 = 2131165233;
			
			// aapt resource value: 0x7f070032
			public const int F75 = 2131165234;
			
			// aapt resource value: 0x7f070033
			public const int F751 = 2131165235;
			
			// aapt resource value: 0x7f070034
			public const int F752 = 2131165236;
			
			// aapt resource value: 0x7f070035
			public const int F753 = 2131165237;
			
			// aapt resource value: 0x7f070036
			public const int F754 = 2131165238;
			
			// aapt resource value: 0x7f070037
			public const int F81 = 2131165239;
			
			// aapt resource value: 0x7f070038
			public const int F82 = 2131165240;
			
			// aapt resource value: 0x7f070039
			public const int F83 = 2131165241;
			
			// aapt resource value: 0x7f07003a
			public const int F84 = 2131165242;
			
			// aapt resource value: 0x7f07003b
			public const int F85 = 2131165243;
			
			// aapt resource value: 0x7f07003c
			public const int F851 = 2131165244;
			
			// aapt resource value: 0x7f07003d
			public const int F852 = 2131165245;
			
			// aapt resource value: 0x7f07003e
			public const int F853 = 2131165246;
			
			// aapt resource value: 0x7f07003f
			public const int F854 = 2131165247;
			
			// aapt resource value: 0x7f070040
			public const int F91 = 2131165248;
			
			// aapt resource value: 0x7f070041
			public const int F92 = 2131165249;
			
			// aapt resource value: 0x7f070042
			public const int F93 = 2131165250;
			
			// aapt resource value: 0x7f070043
			public const int F94 = 2131165251;
			
			// aapt resource value: 0x7f070044
			public const int F95 = 2131165252;
			
			// aapt resource value: 0x7f070045
			public const int F951 = 2131165253;
			
			// aapt resource value: 0x7f070046
			public const int F952 = 2131165254;
			
			// aapt resource value: 0x7f070047
			public const int F953 = 2131165255;
			
			// aapt resource value: 0x7f070048
			public const int F954 = 2131165256;
			
			// aapt resource value: 0x7f070050
			public const int RadioEasy = 2131165264;
			
			// aapt resource value: 0x7f070051
			public const int RadioHard = 2131165265;
			
			// aapt resource value: 0x7f070000
			public const int TextScore = 2131165184;
			
			// aapt resource value: 0x7f07004f
			public const int textView = 2131165263;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int LayoutGame = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int LayoutInstruction = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int LayoutLevel = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Main = 2130903043;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050000
			public const int ApplicationName = 2131034112;
			
			// aapt resource value: 0x7f05000b
			public const int Back = 2131034123;
			
			// aapt resource value: 0x7f050007
			public const int CheckButton = 2131034119;
			
			// aapt resource value: 0x7f050004
			public const int Easy = 2131034116;
			
			// aapt resource value: 0x7f050005
			public const int Hard = 2131034117;
			
			// aapt resource value: 0x7f050002
			public const int Instruction = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int InstructionText = 2131034115;
			
			// aapt resource value: 0x7f05000a
			public const int LoseGame = 2131034122;
			
			// aapt resource value: 0x7f050001
			public const int Play = 2131034113;
			
			// aapt resource value: 0x7f050008
			public const int Score = 2131034120;
			
			// aapt resource value: 0x7f050006
			public const int TextTmp = 2131034118;
			
			// aapt resource value: 0x7f050009
			public const int WinGame = 2131034121;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060000
			public const int Mono_Android_Theme_Splash = 2131099648;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
